config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(settings.ADMIN_URL, admin.site.urls),
    url('^accounts/', include('django.contrib.auth.urls')),
    url('^', include('matcher.carriermatcher.urls', namespace='carriermatcher')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

matcher/carriermatcher/urls.py
from django.conf.urls import url

from matcher.carriermatcher import views

urlpatterns = [
    url(r'^$', views.create_matching_request, name='create_matching_request'),
    url(r'^(?P<pk>\d+)/$', views.matching_request_detail, name='matching_request_detail'),
    url(r'^(?P<pk>\d+)/download/$', views.matching_request_download, name='matching_request_download'),
    url(r'^match/$', views.match_company, name='match_company'),
]

matcher/carriermatcher/models.py
from datetime import datetime

from django.conf import settings
from django.db import models

from .excel_models import CarrierExcel

HELP_TEXT = '''
<h3>Only xls files with following structure</h3>
#6. column: Company <br/>
#15. column: Town <br/>
'''


class MatchingRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    uploaded = models.FileField(
        upload_to='matching',
        help_text=HELP_TEXT,
        max_length=250,
    )
    created_at = models.DateTimeField(default=datetime.now)

    @property
    def carrier_excel(self):
        return CarrierExcel(self.uploaded.read())

matcher/carriermatcher/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import SimpleUploadedFile
from django.forms.formsets import BaseFormSet

from .excel_models import CarrierExcel
from .models import MatchingRequest
from .solr_client import SolrClient


class MatchingRequestForm(forms.ModelForm):

    class Meta:
        model = MatchingRequest
        fields = ('uploaded',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(MatchingRequestForm, self).__init__(*args, **kwargs)

    def clean_uploaded(self):
        uploaded = self.cleaned_data['uploaded']
        try:
            excel = CarrierExcel(uploaded.read())
        except Exception as e:
            raise ValidationError(message='Not appropriate file content: %s' % e)
        else:
            if not excel.is_valid():
                raise ValidationError(message='Not appropriate file content')
        return uploaded

    def save(self, commit=True):
        self.instance.user = self.user
        return super(MatchingRequestForm, self).save(commit)


class MatchCompanyForm(forms.Form):
    name = forms.CharField(required=True)
    city = forms.CharField(required=True)

    def match(self):
        name = self.cleaned_data['name']
        city = self.cleaned_data['city']
        client = SolrClient()
        results = client.carriers_by_name_and_city(name, city)
        return results


class MatchedCompanyForm(forms.Form):
    row_number = forms.IntegerField(widget=forms.HiddenInput)
    company_id = forms.IntegerField(required=False, widget=forms.HiddenInput(
        attrs={'class': 'carrier-id'}
    ))
    agreement_id = forms.CharField(required=False, widget=forms.HiddenInput(
        attrs={'class': 'agreement-id'}
    ))

    def __init__(self, *args, **kwargs):
        super(MatchedCompanyForm, self).__init__(*args, **kwargs)
        self.carrier = None

    def save(self):
        self.carrier.company_id = self.cleaned_data['company_id']
        self.carrier.agreement_versions = self.cleaned_data['agreement_id']


class MatchedCompanyFormset(BaseFormSet):
    form = MatchedCompanyForm
    extra = 0
    can_order = False
    can_delete = False
    min_num = None
    max_num = None
    absolute_max = 1000

    def __init__(self, matching_request, data=None):
        self.matching_request = matching_request
        self.carrier_excel = matching_request.carrier_excel
        initial = [item.attrs() for item in self.carrier_excel]
        super(MatchedCompanyFormset, self).__init__(data=data, initial=initial)

    def add_fields(self, form, index):
        form.carrier = self.carrier_excel[index]

    def save(self):
        for form in self.forms:
            form.save()
        content = self.carrier_excel.save()
        name = 'carrierlist-%d.xls' % self.matching_request.pk
        self.matching_request.uploaded.save(name, SimpleUploadedFile(name, content))

matcher/carriermatcher/views.py
import json
from django.contrib.admin.views.decorators import staff_member_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, TemplateView, DetailView

from .forms import MatchingRequestForm, MatchCompanyForm, \
    MatchedCompanyFormset
from .models import MatchingRequest


class MatchingRequestDetailView(TemplateView):
    template_name = 'carriermatcher/matched_carriers_details.html'

    def get(self, request, *args, **kwargs):
        formset = MatchedCompanyFormset(self.matching_request)
        return self.render(formset)

    def post(self, request, *args, **kwargs):
        formset = MatchedCompanyFormset(
            self.matching_request, data=request.POST)
        if not formset.is_valid():
            return self.render(formset)
        formset.save()
        return redirect('carriermatcher:matching_request_download', self.matching_request.pk)

    def render(self, formset):
        return self.render_to_response({'formset': formset})

    @property
    def matching_request(self):
        if not hasattr(self, '_matching_request'):
            pk = self.kwargs['pk']
            self._matching_request = get_object_or_404(MatchingRequest, pk=pk)
        return self._matching_request

matching_request_detail = staff_member_required(MatchingRequestDetailView.as_view())


class DownloadExcel(DetailView):
    model = MatchingRequest
    template_name = 'carriermatcher/matched_carriers_download.html'

matching_request_download = staff_member_required(DownloadExcel.as_view())


class CreateMatchingRequestView(CreateView):
    template_name = 'carriermatcher/create_matching_request.html'
    form_class = MatchingRequestForm

    def get_form_kwargs(self):
        kwargs = super(CreateMatchingRequestView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('carriermatcher:matching_request_detail', args=(self.object.pk,))

create_matching_request = staff_member_required(CreateMatchingRequestView.as_view())


@staff_member_required
def match_company(request):
    form = MatchCompanyForm(request.GET)
    if not form.is_valid():
        return JsonReponse(form.errors, status=400)
    content = {'matches': form.match()}
    return JsonReponse(content)


class JsonReponse(HttpResponse):

    def __init__(self, content, status=200):
        if isinstance(content, dict):
            content = json.dumps(content)
        content_type = 'application/json'
        super(JsonReponse, self).__init__(
            content, status=status, content_type=content_type)

matcher/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Store Api Integration{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

matcher/templates/carriermatcher/create_matching_request.html
{% extends "admin/base_site.html" %}

{% load static %}
{% block content %}
    <h1>Upload excel file for carrier matching</h1>
    <p>Example file:
        <a href="{% static 'carrier_matcher_template.xls' %}">Carrier Matcher.xml</a>
    </p>
    <form action="{% url "carriermatcher:create_matching_request" %}" method="post"
          enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Upload"/>
    </form>
{% endblock %}

matcher/templates/carriermatcher/matched_carriers_details.html
{% extends "admin/base_site.html" %}
{% load staticfiles %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/carriermatching.css' %}" />
{% endblock %}

{% block extrajs %}
    {{ block.super }}
    <script src="{% static 'js/CarrierMatching.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>Carrier matching</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        <table data-match-url="{% url "carriermatcher:match_company" %}" id='carrier-table'>
            <tr>
                <th>Row</th>
                <th>Name</th>
                <th>City</th>
                <th>Country</th>
                <th class="carrier-matches">Matches</th>
            </tr>
            {% for form in formset %}
                <tr class="carrier-row">
                    <td class="row-number">{{ form.carrier.row_number }}</td>
                    <td class="carrier-name">{{ form.carrier.name }}</td>
                    <td class="carrier-city">{{ form.carrier.city }}</td>
                    <td class="carrier-country">{{ form.carrier.country }}</td>
                    <td class='carrier-matches'>
                        Waiting...
                    </td>
                    <td>
                        {{ form.as_p }}
                    </td>
                </tr>
            {% endfor %}
            <tr class="submit-row">
                <td colspan="5"></td>
                <td colspan="2">
                    <button type="submit" disabled="disabled">
                        Save and download
                    </button>
                </td>
            </tr>
        </table>

    </form>
{% endblock %}

matcher/templates/carriermatcher/matched_carriers_download.html
{% extends "admin/base_site.html" %}


{% block content %}
    <h1>Carrier matching</h1>
    <p>
        Click on link below to download Excel file with matched carriers
    </p>
    <p>
        <a href="{{ object.uploaded.url }}">Matched Carriers XLS</a>
    </p>
    <p>
        If you made mistake, you can match the same file again
        <a href="{% url "carriermatcher:matching_request_detail" object.pk %}">here</a>.
    </p>
{% endblock %}